// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUD_Sample2.Models
{
    public partial class Student
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public long? Age { get; set; }
        public string Rollnumber { get; set; }
    }
}